#!/bin/sh
# This script is only used for developement. It is removed by the 
# distribution process. 

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -tag annot -tag debug -classic-display \
                          -use-ocamlfind"}

action () 
{
    case $1 in
      default)      $OCAMLBUILD tsdl.cmx ;;
      tests)        $OCAMLBUILD tests.otarget ;;
      doc)          shift; pkg-doc $* doc/api-dev.docdir ;;
      api-doc)      shift; pkg-doc $* doc/api.docdir ;;
      clean)        $OCAMLBUILD -clean ;;
      *)            $OCAMLBUILD $* ;;
    esac
} 

if [ $# -eq 0 ]; 
then action default ; 
else action $*; fi
